services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword # Senha do usuário root
      MYSQL_DATABASE: ecom           # Nome do banco de dados
      MYSQL_USER: ecom               # Usuário configurado
      MYSQL_PASSWORD: mypassword     # Senha do usuário configurado
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    restart: no

volumes:
  db_data:

networks:
  app_network: